spring:
  datasource:
    url: jdbc:mysql://mysql:3306/medical_cita?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  cloud:
    config:
      enabled: true
      fail-fast: true
    discovery:
      enabled: true
server:
  port: 8085