# --- Identidad y puerto del Config Server ---
spring.application.name=config-server
server.port=8888

# --- Backend Git ---
spring.cloud.config.server.git.uri=https://github.com/Julio-Cuellar/clinical-managment.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=config,.
spring.cloud.config.server.git.clone-on-start=true

# --- Autenticación HTTPS ---
spring.cloud.config.server.git.username=${GIT_USER}
spring.cloud.config.server.git.password=${GIT_PASSWORD}

# --- Exponer endpoints de Actuator para monitorizar ---
management.endpoints.web.exposure.include=health,info,env,refresh
