spring:
  config:
    import: "optional:configserver:http://localhost:8888"

  application:
    name: agenda-service

  datasource:
    url: jdbc:mysql://localhost:3306/agenda_db?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

  cloud:
    config:
      uri: http://localhost:8888
      enabled: true

server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.jc.clinical_managment.agenda_service: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html